aligner_config:
  model: 'bert-base-multilingual-cased'
  output_file: 'file.txt'
  align_layer: 8

  threshold: 1e-3
  probs_layer: 'softmax'

translator_config:
  batch_size: 4
  model_checkpoint_dir: 'ai4bharat/indictrans2-en-indic-1B'
  
  file_path: "/content/input.txt"
  q_config: '4-bit'

overall_config:
  input_type: 'hf_dataset' # Other options are 'single_language_file' and 'textual_input'
  source_lang: 'en'
  target_lang: 'hi'